"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.pubMedLocales = void 0;
exports.pubMedCopy = pubMedCopy;
const shared = {
    'pt-BR': ['Pesquisar estudos clínicos na ELUCENIA', 'Digite termos científicos, escolha a categoria e a abrangência. Os termos são enviados ao NCBI; não informe dados de pacientes.', 'Termos de busca', 'Categoria do estudo', 'Abrangência', 'Ampla · mais sensível', 'Restrita · mais específica', 'Pesquisar', 'Pesquisando…', 'Limpar', 'Resultados encontrados', 'Nenhum resultado. Revise os termos ou use a busca ampla.', 'Anterior', 'Próxima', 'Página', 'Exportar referências JSON', 'Estratégia aplicada', 'Interpretação da busca pelo PubMed', 'Consultado em', 'As referências mantêm os metadados fornecidos pela NLM.', 'Filtros não avaliam a qualidade de cada estudo. São exibidos até 10.000 registros; refine buscas maiores. Não substitui uma revisão sistemática.', 'Confira os termos, a categoria e a abrangência.', 'O PubMed está indisponível. Tente novamente.', 'Muitas solicitações. Aguarde e tente novamente.', 'A conexão com o PubMed ainda não foi configurada.', 'Fonte: NLM / NCBI PubMed. Sem endosso da NLM.', 'Políticas e aviso de direitos do NCBI', 'Não são reproduzidos resumos nem artigos completos. Os metadados são obtidos ao vivo; a fonte pode corrigir os registros.', 'Estratégias metodológicas oficiais'],
    en: ['Search clinical studies in ELUCENIA', 'Enter scientific search terms, then choose a category and scope. Terms are sent to NCBI; do not enter patient details.', 'Search terms', 'Study category', 'Scope', 'Broad · more sensitive', 'Narrow · more specific', 'Search', 'Searching…', 'Clear', 'Results found', 'No results. Revise your terms or use the broad search.', 'Previous', 'Next', 'Page', 'Export references as JSON', 'Applied search strategy', 'PubMed query translation', 'Retrieved at', 'References retain the metadata supplied by NLM.', 'Filters do not assess individual study quality. Up to 10,000 records are shown; refine larger searches. This does not replace a systematic review.', 'Check the search terms, category and scope.', 'PubMed is unavailable. Please try again.', 'Too many requests. Please wait and try again.', 'The PubMed connection has not yet been configured.', 'Source: NLM / NCBI PubMed. No NLM endorsement.', 'NCBI policies and copyright notice', 'Abstracts and full articles are not reproduced. Metadata is retrieved live; the source may correct records.', 'Official methodological search strategies'],
    es: ['Buscar estudios clínicos en ELUCENIA', 'Introduzca términos científicos y elija una categoría y un alcance. Los términos se envían a NCBI; no introduzca datos de pacientes.', 'Términos de búsqueda', 'Categoría del estudio', 'Alcance', 'Amplio · más sensible', 'Restringido · más específico', 'Buscar', 'Buscando…', 'Limpiar', 'Resultados encontrados', 'No hay resultados. Revise los términos o use la búsqueda amplia.', 'Anterior', 'Siguiente', 'Página', 'Exportar referencias en JSON', 'Estrategia de búsqueda aplicada', 'Interpretación de la consulta por PubMed', 'Consultado el', 'Las referencias conservan los metadatos proporcionados por NLM.', 'Los filtros no evalúan la calidad de cada estudio. Se muestran hasta 10.000 registros; refine las búsquedas más amplias. No sustituye una revisión sistemática.', 'Compruebe los términos, la categoría y el alcance.', 'PubMed no está disponible. Inténtelo de nuevo.', 'Demasiadas solicitudes. Espere e inténtelo de nuevo.', 'La conexión con PubMed aún no se ha configurado.', 'Fuente: NLM / NCBI PubMed. Sin respaldo de NLM.', 'Políticas y aviso de derechos de NCBI', 'No se reproducen resúmenes ni artículos completos. Los metadatos se obtienen en directo; la fuente puede corregir los registros.', 'Estrategias metodológicas oficiales'],
    fr: ['Rechercher des études cliniques dans ELUCENIA', 'Saisissez des termes scientifiques, puis choisissez une catégorie et une portée. Les termes sont envoyés au NCBI ; ne saisissez pas de données de patients.', 'Termes de recherche', 'Catégorie d’étude', 'Portée', 'Large · plus sensible', 'Étroite · plus spécifique', 'Rechercher', 'Recherche en cours…', 'Effacer', 'Résultats trouvés', 'Aucun résultat. Modifiez les termes ou utilisez la recherche large.', 'Précédente', 'Suivante', 'Page', 'Exporter les références en JSON', 'Stratégie de recherche appliquée', 'Interprétation de la requête par PubMed', 'Consulté le', 'Les références conservent les métadonnées fournies par la NLM.', 'Les filtres n’évaluent pas la qualité de chaque étude. Jusqu’à 10 000 références sont affichées ; affinez les recherches plus larges. Cela ne remplace pas une revue systématique.', 'Vérifiez les termes, la catégorie et la portée.', 'PubMed est indisponible. Veuillez réessayer.', 'Trop de requêtes. Patientez, puis réessayez.', 'La connexion à PubMed n’a pas encore été configurée.', 'Source : NLM / NCBI PubMed. Sans approbation de la NLM.', 'Politiques et avis de droits du NCBI', 'Les résumés et les articles complets ne sont pas reproduits. Les métadonnées sont obtenues en direct ; la source peut corriger les références.', 'Stratégies méthodologiques officielles'],
    de: ['Klinische Studien in ELUCENIA suchen', 'Geben Sie wissenschaftliche Suchbegriffe ein und wählen Sie Kategorie und Suchumfang. Die Begriffe werden an NCBI gesendet; geben Sie keine Patientendaten ein.', 'Suchbegriffe', 'Studienkategorie', 'Suchumfang', 'Breit · höhere Sensitivität', 'Eng · höhere Spezifität', 'Suchen', 'Suche läuft…', 'Zurücksetzen', 'Gefundene Ergebnisse', 'Keine Ergebnisse. Ändern Sie die Begriffe oder verwenden Sie die breite Suche.', 'Zurück', 'Weiter', 'Seite', 'Referenzen als JSON exportieren', 'Angewandte Suchstrategie', 'Interpretation der Suchanfrage durch PubMed', 'Abgerufen am', 'Die Referenzen behalten die von NLM bereitgestellten Metadaten bei.', 'Filter bewerten nicht die Qualität einzelner Studien. Bis zu 10.000 Datensätze werden angezeigt; grenzen Sie größere Suchen ein. Dies ersetzt keine systematische Übersichtsarbeit.', 'Prüfen Sie die Suchbegriffe, Kategorie und den Suchumfang.', 'PubMed ist nicht verfügbar. Versuchen Sie es erneut.', 'Zu viele Anfragen. Warten Sie und versuchen Sie es erneut.', 'Die Verbindung zu PubMed wurde noch nicht eingerichtet.', 'Quelle: NLM / NCBI PubMed. Keine Empfehlung durch NLM.', 'NCBI-Richtlinien und Urheberrechtshinweis', 'Zusammenfassungen und vollständige Artikel werden nicht wiedergegeben. Metadaten werden aktuell abgerufen; die Quelle kann Datensätze korrigieren.', 'Offizielle methodische Suchstrategien'],
    it: ['Cercare studi clinici in ELUCENIA', 'Inserisci termini scientifici e scegli una categoria e un ambito. I termini vengono inviati a NCBI; non inserire dati dei pazienti.', 'Termini di ricerca', 'Categoria dello studio', 'Ambito', 'Ampio · più sensibile', 'Ristretto · più specifico', 'Cerca', 'Ricerca in corso…', 'Cancella', 'Risultati trovati', 'Nessun risultato. Rivedi i termini o usa la ricerca ampia.', 'Precedente', 'Successiva', 'Pagina', 'Esporta riferimenti in JSON', 'Strategia di ricerca applicata', 'Interpretazione della ricerca da parte di PubMed', 'Consultato il', 'I riferimenti mantengono i metadati forniti da NLM.', 'I filtri non valutano la qualità dei singoli studi. Vengono mostrati fino a 10.000 record; restringi le ricerche più ampie. Non sostituisce una revisione sistematica.', 'Controlla i termini, la categoria e l’ambito.', 'PubMed non è disponibile. Riprova.', 'Troppe richieste. Attendi e riprova.', 'La connessione a PubMed non è ancora stata configurata.', 'Fonte: NLM / NCBI PubMed. Nessuna approvazione da parte di NLM.', 'Politiche e avviso sui diritti di NCBI', 'Non vengono riprodotti abstract o articoli completi. I metadati vengono recuperati in tempo reale; la fonte può correggere i record.', 'Strategie metodologiche ufficiali'],
    ar: ['البحث عن الدراسات السريرية داخل ELUCENIA', 'أدخل مصطلحات علمية، ثم اختر الفئة ونطاق البحث. تُرسل المصطلحات إلى NCBI؛ لا تدخل بيانات المرضى.', 'مصطلحات البحث', 'فئة الدراسة', 'نطاق البحث', 'واسع · حساسية أعلى', 'ضيق · نوعية أعلى', 'بحث', 'جارٍ البحث…', 'مسح', 'النتائج الموجودة', 'لا توجد نتائج. عدّل المصطلحات أو استخدم البحث الواسع.', 'السابقة', 'التالية', 'الصفحة', 'تصدير المراجع بصيغة JSON', 'استراتيجية البحث المطبقة', 'تفسير PubMed لاستعلام البحث', 'تاريخ الاسترجاع', 'تحتفظ المراجع بالبيانات الوصفية التي توفرها NLM.', 'لا تقيّم المرشحات جودة كل دراسة. يُعرض ما يصل إلى ١٠٬٠٠٠ سجل؛ ضيّق نطاق البحث إن زاد العدد. لا يغني ذلك عن المراجعة المنهجية.', 'تحقق من المصطلحات والفئة ونطاق البحث.', 'PubMed غير متاح. حاول مرة أخرى.', 'طلبات كثيرة. انتظر ثم حاول مرة أخرى.', 'لم يُضبط الاتصال بـ PubMed بعد.', 'المصدر: NLM / NCBI PubMed. دون تأييد من NLM.', 'سياسات NCBI وإشعار حقوق النشر', 'لا تُعاد نشر الملخصات أو المقالات الكاملة. تُسترجع البيانات الوصفية مباشرة؛ وقد يصحح المصدر السجلات.', 'استراتيجيات البحث المنهجية الرسمية'],
    zh: ['在 ELUCENIA 内检索临床研究', '输入科学检索词，然后选择研究类别和检索范围。检索词将发送至 NCBI；请勿输入患者信息。', '检索词', '研究类别', '检索范围', '宽范围 · 更高敏感度', '窄范围 · 更高特异度', '检索', '正在检索…', '清除', '检索结果总数', '没有结果。请修改检索词或使用宽范围检索。', '上一页', '下一页', '页码', '将参考文献导出为 JSON', '已应用的检索策略', 'PubMed 对检索式的解释', '检索时间', '参考文献保留 NLM 提供的原始元数据。', '筛选条件不评价单项研究的质量。最多显示 10,000 条记录；结果更多时请缩小检索范围。这不能替代系统综述。', '请检查检索词、研究类别和检索范围。', 'PubMed 暂不可用。请重试。', '请求过多。请稍候再试。', '尚未配置 PubMed 连接。', '数据来源：NLM / NCBI PubMed。不代表 NLM 的认可。', 'NCBI 政策及版权声明', '不转载摘要或全文。元数据实时获取；数据来源可能修正记录。', '官方方法学检索策略'],
    ja: ['ELUCENIA 内で臨床研究を検索', '科学的な検索語を入力し、研究カテゴリーと検索範囲を選択してください。検索語は NCBI に送信されます。患者情報を入力しないでください。', '検索語', '研究カテゴリー', '検索範囲', '広い範囲 · 感度重視', '狭い範囲 · 特異度重視', '検索', '検索中…', 'クリア', '検索結果件数', '結果がありません。検索語を変更するか、広い範囲で検索してください。', '前へ', '次へ', 'ページ', '参考文献を JSON でエクスポート', '適用した検索式', 'PubMed による検索式の解釈', '取得日時', '参考文献は NLM が提供するメタデータを保持します。', 'フィルターは個々の研究の質を評価しません。最大 10,000 件を表示します。それ以上の場合は検索を絞り込んでください。システマティックレビューの代わりにはなりません。', '検索語、カテゴリー、検索範囲を確認してください。', 'PubMed を利用できません。再試行してください。', 'リクエストが多すぎます。しばらく待ってから再試行してください。', 'PubMed への接続がまだ設定されていません。', '出典：NLM / NCBI PubMed。NLM による推奨を意味しません。', 'NCBI のポリシーと著作権に関する注意事項', '抄録や全文は転載しません。メタデータはリアルタイムで取得され、提供元で修正される場合があります。', '公式の方法論的検索式'],
    hi: ['ELUCENIA में नैदानिक अध्ययनों की खोज', 'वैज्ञानिक खोज शब्द दर्ज करें, फिर श्रेणी और खोज का दायरा चुनें। शब्द NCBI को भेजे जाते हैं; रोगियों की जानकारी दर्ज न करें।', 'खोज शब्द', 'अध्ययन की श्रेणी', 'खोज का दायरा', 'व्यापक · अधिक संवेदनशील', 'संकीर्ण · अधिक विशिष्ट', 'खोजें', 'खोज जारी है…', 'साफ़ करें', 'प्राप्त परिणाम', 'कोई परिणाम नहीं। शब्द बदलें या व्यापक खोज का उपयोग करें।', 'पिछला', 'अगला', 'पृष्ठ', 'संदर्भ JSON में निर्यात करें', 'लागू खोज रणनीति', 'PubMed द्वारा खोज की व्याख्या', 'प्राप्ति का समय', 'संदर्भों में NLM द्वारा दिए गए मेटाडेटा यथावत रहते हैं।', 'फ़िल्टर प्रत्येक अध्ययन की गुणवत्ता का आकलन नहीं करते। अधिकतम 10,000 रिकॉर्ड दिखाए जाते हैं; अधिक परिणाम हों तो खोज सीमित करें। यह व्यवस्थित समीक्षा का विकल्प नहीं है।', 'खोज शब्द, श्रेणी और दायरा जाँचें।', 'PubMed उपलब्ध नहीं है। फिर प्रयास करें।', 'बहुत अधिक अनुरोध। प्रतीक्षा करें और फिर प्रयास करें।', 'PubMed का कनेक्शन अभी कॉन्फ़िगर नहीं किया गया है।', 'स्रोत: NLM / NCBI PubMed। NLM के समर्थन का दावा नहीं।', 'NCBI की नीतियाँ और कॉपीराइट सूचना', 'सारांश या पूरे लेख पुनर्प्रकाशित नहीं किए जाते। मेटाडेटा सीधे प्राप्त किए जाते हैं; स्रोत रिकॉर्ड सुधार सकता है।', 'आधिकारिक पद्धतिगत खोज रणनीतियाँ'],
};
const categories = {
    'pt-BR': ['Terapia', 'Diagnóstico', 'Etiologia', 'Prognóstico', 'Regras de predição clínica'],
    en: ['Therapy', 'Diagnosis', 'Etiology', 'Prognosis', 'Clinical prediction guides'],
    es: ['Tratamiento', 'Diagnóstico', 'Etiología', 'Pronóstico', 'Reglas de predicción clínica'],
    fr: ['Traitement', 'Diagnostic', 'Étiologie', 'Pronostic', 'Règles de prédiction clinique'],
    de: ['Therapie', 'Diagnostik', 'Ätiologie', 'Prognose', 'Klinische Vorhersageregeln'],
    it: ['Terapia', 'Diagnosi', 'Eziologia', 'Prognosi', 'Regole di predizione clinica'],
    ar: ['العلاج', 'التشخيص', 'المسببات', 'المآل', 'أدلة التنبؤ السريري'],
    zh: ['治疗', '诊断', '病因', '预后', '临床预测规则'],
    ja: ['治療', '診断', '病因', '予後', '臨床予測ルール'],
    hi: ['उपचार', 'निदान', 'रोगकारण', 'पूर्वानुमान', 'नैदानिक पूर्वानुमान नियम'],
};
const keys = ['title', 'intro', 'query', 'category', 'scope', 'broad', 'narrow', 'search', 'searching', 'clear', 'found', 'empty', 'previous', 'next', 'page', 'export', 'strategy', 'translatedQuery', 'retrieved', 'original', 'limits', 'invalid', 'unavailable', 'rate', 'configured', 'source', 'policy', 'copyright', 'help'];
function pubMedCopy(locale = 'pt-BR') {
    const selected = Object.hasOwn(shared, locale) ? locale : 'en';
    return { ...Object.fromEntries(keys.map((key, index) => [key, shared[selected][index]])), categories: categories[selected] };
}
exports.pubMedLocales = Object.keys(shared);
